version : '3.2'

services :

    python:
      build: 
        context: .
        dockerfile: Dockerfile-python
      image: python_django:dev
      container_name: python_django_books
      volumes:
        - /home/saurabh/django_projects/books_info/:/home/docker/
      # command: python source/manage.py runserver 0.0.0.0:8005
      command: tail -f /dev/null   
      ports:
        - 8000:8005      #(localhost port:container port) 
